name: dart_app_third_app
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0-221.0.dev

# Add regular dependencies here.
dependencies:
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
